name: credit_card_fraud_detection

channels:
  - defaults

dependencies:
    - python>=3.6
    - ipython
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas
    - scipy
    - seaborn
    - sphinx >= 1.6
    - pip >= 18.0
    - pip:
        - GitPython
        - progressbar2
        - cosmo-utils
        - configparser
        - sphinx-astropy
        - sphinx_rtd_theme
